name: MLflow CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 pandas scikit-learn

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run MLProject
        id: train_model
        run: |
          mlflow run MLProject --entry-point main --env-manager local
          # Extract RUN_ID from mlruns
          RUN_ID=$(python -c "import mlflow; print(mlflow.search_runs().loc[0, 'run_id'])")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/model" -n "syaifulhendri/iris-predictor:latest" --env-manager local
          docker push syaifulhendri/iris-predictor:latest
